apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ai-sre
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      # TODO: Configure Prometheus
    scrape_configs:
    # TODO: Add scrape targets
